### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by cat-6sephiruth** [THUFutureLab/gluon-face#32]
Help me. I want to run arcface.

This problem occurs.
============
[03:25:12] src/base.cc:84: Upgrade advisory: this mxnet has been built against cuDNN lib version 7301, which is older thanthe oldest version tested by CI (7600).  Set MXNET_CUDNN_LIB_CHECKING=0 to quiet this warning.Traceback (most recent call last):  File "train_arcloss.py", line 93, in <module>    warmup_lr=lr / 10, warmup_epochs=warmup_epochs, 3='linear'TypeError: __init__() got an unexpected keyword argument 'warmup_lr'
=============

In the gluon docs,
warmup_lr, warmup_epochs, and warmup_mode
 don't seem to be commented.

So when I commented out line 93, I also ran into the following problem:

It seems to work well but at the end
===============================
Traceback (most recent call last):  File "train_arcloss.py", line 110, in <module>    lr_scheduler.update(i, epoch)
TypeError: update() takes 2 positional arguments but 3 were given
================================

**Comment by haoxintong** [comment]
Hi,
The script `examples/.../train_arcloss.py` using Scheduler from gluoncv, and there are some breaking change in recent releases. I'm sorry about keeping the breaking code in this repo, now the examples just show gluon users how to use this repo to get face models.

So we suggest training with `scripts/train_script.py`, which has been tested and could produce sota model.

**Comment by 6sephiruth** [comment]
<img width="1124" alt="스크린샷 2019-09-03 오전 11 11 10" src="https://user-images.githubusercontent.com/13704709/64139373-97ff6400-ce3b-11e9-8209-a45f50eb1c2c.png">

Thank you very much for your answer.
I'm studying arcface. Should we do it like this?
I only used two gpu, so I changed the number of gpu and changed the batch size.
However, it does not move on to the next step, as shown in the picture.

**Comment by cat-6sephiruth** [comment]
Thank you very much for your answer.
I'm doing it in Arcface and I'm doing it with two gpu.
But do you know why when there's an error in the train and there's a problem that breaks?
<img width="1013" alt="스크린샷 2019-09-03 오후 2 43 15" src="https://user-images.githubusercontent.com/13704709/64146778-30f0a800-ce59-11e9-92c8-bd87c7141e01.png">

**Comment by cat-6sephiruth** [comment]
I've repeated it many times, but I can't learn from the same problem.

**Comment by haoxintong** [comment]
The early training process of arc loss is not stable, so we always do warm up training using L2-Norm Softmax for several epochs or until the val acc reach 0.90+.

Besides, in our 8 gpu training script we use a larger initial learning rate, as we have a large batch size like 1024 or 2048. If there are only 2 GPU, you should try a small learning rate at begining.

**Comment by cat-6sephiruth** [comment]
Thank you for your prompt reply.
I am grateful for your prompt reply by lowering the reading rate and warm
As I said, I lowered the reading rate and warm up it.
I think 32 and 58 of line  (*train_script.py)
We changed the reading rate to 0.01 and warm up iers to 40000, but we still have a problem.

**Comment by haoxintong** [comment]
The Nan problem will also be caused by reasons like:
- The input data contain Nan or some images are broken. 
- The scale parameter is setting too large, and after output sum the result is out of float32 range.

To find out what is the exactly reason, you should start with the basic pipeline, training a model with softmax. If the quality of dataset is good enough, we could get a model that val acc over 99.0+ just using softmax. Then you can finetune from this model with any margin-based losses and check if they could get better perfomance.

To be honest, if your target is to get a recognition model but dont care about what happened in this process, `insight face` project is a better choice, as there are more pre-trained models of different sizes and computing efficiency. 

This project is for those not familiar with MXNet symbol api and face recognition, we hope that users could learn the basic usage of MXNet gluon and how to modify our examples to get their own ones. This is not hard as gluon api is almost same with pytorch.  Also most losses of recent years are implemented so users could easily modify and re-produce methods from latest paper.

I hope this will help, thanks for your issue. :D
